/**
 * Pre-designed Carousel Poster Templates for the Homepage Showcase
 */

export const PRESET_TEMPLATES = [
  {
    id: 'tpl_ai_breaking',
    name: 'AI Breaking News',
    tagline: 'High impact tech headlines & emergency updates',
    themeId: 'dark_lime',
    slidesCount: 3,
    coverTitle: 'OpenAI kills model before launch',
    slides: [
      {
        id: 't1_s1',
        headline: "OpenAI just killed its own model before launch",
        subtext: "GPT-6.1 'Astra' got scrapped for being too deceptive in testing. The AI was literally too shady to ship, a day before DevDay. We are so back (to the safety meetings).",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Photo: OpenAI',
        fontChoice: 'Anton',
        themeId: 'dark_lime',
      },
      {
        id: 't1_s2',
        headline: "Nvidia wants to be the seatbelt of the AI world",
        subtext: "New Open Agent Safety Platform, 100+ companies signed on, claims it would've stopped the Hugging Face breach. Plus a casual $150B buyback. Jensen stays winning.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Photo: Nvidia',
        fontChoice: 'Anton',
        themeId: 'dark_lime',
      },
      {
        id: 't1_s3',
        headline: "Congress finally discovered AI exists",
        subtext: "Florida wants OpenAI in court, Sanders and AOC want to ban superintelligence, and Trump wants an 'AI Force' branch. Everyone has a plan. None of them agree.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Source: Senate Hearings',
        fontChoice: 'Anton',
        themeId: 'dark_lime',
      }
    ]
  },
  {
    id: 'tpl_cyber_roast',
    name: 'Tech Roast Weekly',
    tagline: 'Cyberpunk neon aesthetic with sharp internet roasts',
    themeId: 'neon_cyber',
    slidesCount: 3,
    coverTitle: 'Why your startup is actually an Excel sheet',
    slides: [
      {
        id: 't2_s1',
        headline: "Your startup is just a 50-line Python wrapper",
        subtext: "Raised $40M at a $250M valuation to call the Anthropic API with a custom system prompt. The pitch deck has more CSS animations than the actual product.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Meme: @techbro',
        fontChoice: 'Anton',
        themeId: 'neon_cyber',
      },
      {
        id: 't2_s2',
        headline: "Engineers spend 8 hours debugging 2 lines of CSS",
        subtext: "It was a missing closing bracket and a z-index set to 999999. The coffee machine broke at 3 AM. Production deploy scheduled for 4:45 PM on Friday.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Reddit /r/ProgrammerHumor',
        fontChoice: 'Anton',
        themeId: 'neon_cyber',
      },
      {
        id: 't2_s3',
        headline: "AGI predicted to arrive next Tuesday at 3 PM",
        subtext: "Sam Altman tweeted a cryptic single letter. Tech Twitter wrote 40,000 threads analyzing the font kerning. The stock market reacted with mild panic.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'X / Tech Rumors',
        fontChoice: 'Anton',
        themeId: 'neon_cyber',
      }
    ]
  },
  {
    id: 'tpl_midnight_radar',
    name: 'Obsidian Funding Radar',
    tagline: 'Deep slate gradient for venture capital & tech launches',
    themeId: 'midnight_slate',
    slidesCount: 3,
    coverTitle: 'Autonomous Agents cross $2B in funding',
    slides: [
      {
        id: 't3_s1',
        headline: "Autonomous agent startups bag $2.4B in Q3",
        subtext: "Investors are throwing term sheets at anything with 'Agentic Protocol' in the name. Founders are already buying Patagonia vests in bulk.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'PitchBook Data',
        fontChoice: 'Archivo Black',
        themeId: 'midnight_slate',
      },
      {
        id: 't3_s2',
        headline: "Open source models match closed frontier labs",
        subtext: "New 70B parameter weights released with Apache 2.0 license. Run it on your MacBook or a dual 4090 rig. Cloud providers in shambles.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Hugging Face Hub',
        fontChoice: 'Archivo Black',
        themeId: 'midnight_slate',
      },
      {
        id: 't3_s3',
        headline: "Compute is the new oil of the digital era",
        subtext: "Nuclear reactors getting restarted to power AI data centers in Pennsylvania. GPU clusters now qualify for sovereign debt collateral.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Bloomberg Intelligence',
        fontChoice: 'Archivo Black',
        themeId: 'midnight_slate',
      }
    ]
  },
  {
    id: 'tpl_editorial_light',
    name: 'Editorial Intelligence',
    tagline: 'High-contrast light minimalist journal format',
    themeId: 'clean_light',
    slidesCount: 3,
    coverTitle: 'The Future of AI Architecture',
    slides: [
      {
        id: 't4_s1',
        headline: "Reasoning models shift the paradigm of scale",
        subtext: "Test-time compute scaling is replacing pure pre-training brute force. Thinking tokens allow models to self-correct before generating answers.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'AI Research Journal',
        fontChoice: 'Anton',
        themeId: 'clean_light',
      },
      {
        id: 't4_s2',
        headline: "Synthetic data pipelines outpace human text",
        subtext: "High quality verifiable proofs and simulated environments are training the next frontier models. The internet text archive has officially peaked.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'DeepMind Paper',
        fontChoice: 'Anton',
        themeId: 'clean_light',
      },
      {
        id: 't4_s3',
        headline: "Local AI devices finally become practical",
        subtext: "Sub-4-bit quantization and unified memory architectures allow 14B models to run smoothly on edge hardware without internet access.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Hardware Lab',
        fontChoice: 'Anton',
        themeId: 'clean_light',
      }
    ]
  },
  {
    id: 'tpl_emerald_matrix',
    name: 'Deep Emerald Matrix',
    tagline: 'Silicon & supercomputing hardware spotlight',
    themeId: 'emerald_matrix',
    slidesCount: 3,
    coverTitle: 'Next-Gen Silicon Architectures',
    slides: [
      {
        id: 't5_s1',
        headline: "Liquid cooled wafer scale chips unveiled",
        subtext: "A single piece of silicon with 4 Trillion transistors and 900,000 AI cores. Consumes 23 Kilowatts and requires specialized datacenter plumbing.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Semiconductor Review',
        fontChoice: 'Archivo Black',
        themeId: 'emerald_matrix',
      },
      {
        id: 't5_s2',
        headline: "Optical interconnects break memory bottlenecks",
        subtext: "Photonic laser communication between GPU nodes delivers 10x bandwidth at 1/5th the power consumption of copper wires.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Optics Today',
        fontChoice: 'Archivo Black',
        themeId: 'emerald_matrix',
      },
      {
        id: 't5_s3',
        headline: "Custom TPUs claim leadership in inference efficiency",
        subtext: "Seventh generation tensor processors reduce per-token inference cost by 65%. Scale out clusters now span multiple continents.",
        image: null,
        fit: 'cover',
        focal: 50,
        credit: 'Cloud Hardware',
        fontChoice: 'Archivo Black',
        themeId: 'emerald_matrix',
      }
    ]
  }
];
